from enum import IntEnum

class AccountMergeCollisionPolicies(IntEnum):
    REPOINT = 0
    DROP_LOSER_ON_COLLISION = 1
    DROP_LOSER_ROW = 2
    SPECIAL_DECK_TREE = 3
    SPECIAL_LICENSE_TRANSFER = 4
    SPECIAL_DEVICE_MERGE = 5
    SPECIAL_SESSION_MIGRATE = 6
    SPECIAL_INFORMATION_SOURCE_DEDUP = 7
    SPECIAL_DAILY_ACTIVITY_REKEY = 8
