from enum import IntEnum

class AdminListTypes(IntEnum):
    PAID_DECKS = 0
    REVENUE_BY_DECK = 1
    ADMIN_EMAILS = 2
    RELEASE_NOTES = 3
    ORGANIZATIONS = 4
    ALERTS = 5
    RATE_LIMIT_EVENTS = 6
    ADMIN_AUDIT_EVENTS = 7
    MAINTENANCE_WINDOWS = 8
    ORGANIZATION_MEMBERS = 9
    PROMO_CODES = 10
    PROMO_CODE_REDEEMERS = 11
