from enum import IntEnum

class TaskTypes(IntEnum):
    UNKNOWN = 0
    EXTRACT_FIGURES = 1
    SIMILARITY_SEARCH = 2
    COUNT_WORDS = 3
    EXTRACT_DOCUMENT_CONTENT = 4
    DETERMINE_TOPICS = 5
    GENERATE_FLASHCARDS = 6
    GENERATE_STUDY_MATERIAL = 7
    GENERATE_MOCK_TESTS = 8
    MAP_TOPICS_WITH_CONTENT = 9
    DETERMINE_NUM_QUESTIONS_TO_GENERATE_FOR_EACH_TOPIC = 10
    PROCESS_SYLLABUS = 11
    EXTRACT_DOCUMENT_PAGES = 12
    WAIT = 13
    PREPARE_FOR_GENERATION = 14
    PREPARE_FOR_SIMILARITY_SEARCH = 15
    PREPARE_IMAGES = 16
    FLASHCARD_GENERATION_WORKER = 17
    STUDY_MATERIAL_GENERATION_WORKER = 18
    MOCK_TEST_GENERATION_WORKER = 19
    PROCESS_IMAGE_SYLLABUS = 20
    PREPARE_IMAGES_WORKER = 21
    JUDGE_SHADOW_PAIRS = 22
    FETCH_WEB_CONTENT = 23
    OCR_PDF = 24
    BEAUTIFY_DECK_SHORT_NAMES = 25
    ANALYZE_DECK_PERFORMANCE = 26
    GENERATE_CURATED_STUDY_MATERIAL = 27
    ENHANCE_IMAGES = 28
