import MockTestItem from "./MockTestItem.js";
import { mockTestItemTypes } from "../../Enumerations/MockTestItemTypes.js";

class MockTestQuestion extends MockTestItem
{
    #question = "";
    #answer = ""; // The student's recorded answer for this attempt
    #expectedAnswer = ""; // The correct answer/rubric generated by the LLM
    #answerReason = "";
    // Step-by-step working a student would write out to reach the
    // expected answer. Populated by the generator only for solvable
    // questions (math/physics/etc.) when the user enabled "show solving
    // steps"; left blank for purely subjective answers. The user can
    // hand-edit this later in the mock-test editor.
    #solvingSteps = "";
    #marks = 1;
    #score = 0; // The score awarded after evaluation
    // Examiner-style HTML note attached during evaluation. Populated only
    // when the grader has something useful to surface to the candidate
    // (wrong answer, partial credit justification, factual slip, etc.).
    // Empty string means the Answer Key page will not render a remarks block.
    #remarks = "";
    #additionalData = {};

    constructor(id, question = "", expectedAnswer = "", answerReason = "", marks = 1, answer = "", score = 0, additionalData = {}, solvingSteps = "", remarks = "")
    {
        super(id, mockTestItemTypes.QUESTION);
        this.#question = question;
        this.#expectedAnswer = expectedAnswer;
        this.#answerReason = answerReason;
        this.#marks = marks;
        this.#answer = answer;
        this.#score = score;
        this.#additionalData = additionalData;
        this.#solvingSteps = solvingSteps;
        this.#remarks = remarks;
    }

    getQuestion() { return this.#question; }
    setQuestion(value) { this.#question = value; }

    getAnswer() { return this.#answer; }
    setAnswer(value) { this.#answer = value; }

    getExpectedAnswer() { return this.#expectedAnswer; }
    setExpectedAnswer(value) { this.#expectedAnswer = value; }

    getAnswerReason() { return this.#answerReason; }
    setAnswerReason(value) { this.#answerReason = value; }

    getSolvingSteps() { return this.#solvingSteps; }
    setSolvingSteps(value) { this.#solvingSteps = value || ""; }

    getMarks() { return this.#marks; }
    setMarks(value) { this.#marks = value; }

    getScore() { return this.#score; }
    setScore(value) { this.#score = value; }

    getRemarks() { return this.#remarks; }
    setRemarks(value) { this.#remarks = value || ""; }

    getAdditionalData() { return this.#additionalData; }
    setAdditionalData(value) { this.#additionalData = value; }

    toJson()
    {
        return {
            ...super.toJson(),
            question: this.#question,
            answer: this.#answer,
            expectedAnswer: this.#expectedAnswer,
            answerReason: this.#answerReason,
            solvingSteps: this.#solvingSteps,
            marks: this.#marks,
            score: this.#score,
            remarks: this.#remarks,
            additionalData: this.#additionalData
        };
    }

    static fromJson(json)
    {
        return new MockTestQuestion(
            json.id,
            json.question,
            json.expectedAnswer,
            json.answerReason,
            json.marks,
            json.answer,
            json.score,
            json.additionalData || {},
            json.solvingSteps || "",
            json.remarks || ""
        );
    }
}

export default MockTestQuestion;
