export const questionTypes =
{
  MULTIPLE_CHOICE: 0,
  MULTIPLE_CORRECT: 1,
  OBJECTIVE_SINGLE_WORD_OR_PHRASE: 2,
  SHORT_SUBJECTIVE: 3,
  MEDIUM_SUBJECTIVE: 4,
  LONG_SUBJECTIVE: 5,
  VERY_LONG_SUBJECTIVE: 6,
}
