const visualKinds =
{
  EQUATION: 0,
  CHEMICAL_STRUCTURE: 1,
  RAY_DIAGRAM: 2,
  CIRCUIT_DIAGRAM: 3,
  FREE_BODY_DIAGRAM: 4,
  GRAPH: 5,
  GEOMETRIC_CONSTRUCTION: 6,
  FLOW_OR_PROCESS: 7,
  HIERARCHY_OR_TAXONOMY: 8,
  ILLUSTRATIVE_OR_CONCEPTUAL: 9,
}

module.exports = { visualKinds };
