class MockTestEvaluationConstants:
    GRADING_BATCH_SIZE_BY_TYPE = {"MULTIPLE_CHOICE":15,"MULTIPLE_CORRECT":15,"OBJECTIVE_SINGLE_WORD_OR_PHRASE":15,"SHORT_SUBJECTIVE":10,"MEDIUM_SUBJECTIVE":7,"LONG_SUBJECTIVE":5,"VERY_LONG_SUBJECTIVE":3}
    OFFLINE_GRADABLE_QUESTION_TYPES = ["MULTIPLE_CHOICE","MULTIPLE_CORRECT"]
    SEMANTIC_SIMILARITY_AUTOFULL_THRESHOLD_BY_TYPE = {"OBJECTIVE_SINGLE_WORD_OR_PHRASE":0.92,"SHORT_SUBJECTIVE":0.94,"MEDIUM_SUBJECTIVE":0.96,"LONG_SUBJECTIVE":0.97,"VERY_LONG_SUBJECTIVE":0.98}
    SEMANTIC_SIMILARITY_INPUT_TOKEN_CAP = 2000
    PROMPT_BODY_TOKEN_CAP_PER_BATCH = 20000
    MAX_BATCHES_PER_TASK = 200
    FALLBACK_GRADING_BATCH_SIZE = 5
    ATTEMPT_INPUT_FILENAME = 'Attempt.json'
    GRADED_ATTEMPT_OUTPUT_FILENAME = 'GradedAttempt.json'
    TRANSCRIPTION_REQUEST_FILENAME = 'TranscriptionRequest.json'
    TRANSCRIBED_ANSWERS_OUTPUT_FILENAME = 'TranscribedAnswers.json'
