class PaidDeckShareConstants:
    DEEP_LINK_ROUTE_PATH = '/PaidDeck'
    DEEP_LINK_DECK_ID_QUERY_PARAMETER = 'id'
    PENDING_DECK_ID_COOKIE_NAME = 'pendingPaidDeckId'
    PENDING_DECK_ID_COOKIE_MAX_AGE_SECONDS = 600
    DETAILS_ENDPOINT_PATH = '/PaidDecks/Details'
    QR_MODULE_TARGET_PIXEL_SIZE = 1024
    QR_QUIET_ZONE_MODULES = 4
