class LicenseConstants
{
    static MAX_DEVICES_PER_USER = 4;
    static OFFLINE_GRACE_DAYS_FOR_DEVICE_SIGNOUT = 7;
    static KEY_ROTATION_INTERVAL_DAYS = 7;
    static PAID_DECK_CONTENT_KEY_ROTATION_INTERVAL_DAYS = 30;
    static PAID_DECK_PASSWORD_PBKDF2_ITERATIONS = 100000;
    static PAID_DECK_ENTITY_FETCH_BATCH_LIMIT = 10;
    static OFFLINE_SESSION_HARD_EXPIRY_DAYS = 30;
    static HEARTBEAT_INTERVAL_MILLISECONDS = 300000;
    static MAX_PAID_DECK_COPIES_PER_USER = 4;
    static PAID_DECK_FIRST_INSTANCE_ID = '1';
    static MAX_PAID_DECK_ENTITIES_PER_USER = 200000;
}

export default LicenseConstants;
