const { PacketronRequest, PacketronResponse } = require("@gamiumgamers/packetron");
const InformationSource = require("../../Globals/Model/InformationSource");
const { getUser } = require("../Helpers/GetUser");
const path = require("path");
const { getFileExtensionFromMimeType } = require("../../Globals/UtilityFunctions.js/GetFileExtensionFromMimeType");
const { computeFileSha512Hash } = require("../../Globals/UtilityFunctions.js/ComputeFileSha512Hash");
const Persistence = require("../../Globals/Classes/Persistence");
const { storageTargets } = require("../../Globals/Enumerations/StorageTargets");
const InformationSourceQueryEngine = require("../../Globals/Classes/Database/InformationSourceQueryEngine");
const PersistenceConstants = require("../../Globals/Constants/PersistenceConstants");
const { joinPath } = require("../../Globals/UtilityFunctions.js/JoinPath");
const { ocrModes } = require("../../Globals/Enumerations/OcrModes");
const TaskDescriptor = require("../../Globals/Classes/Task/TaskDescriptor");
const { taskTypes } = require("../../Globals/Enumerations/TaskTypes");
const { taskExecutionTargets } = require("../../Globals/Enumerations/TaskExecutionTargets");
const TaskManager = require("../../Globals/Classes/Task/TaskManager");
const { finalizeOcrUpload } = require("./Helpers/FinalizeOcrUpload");
const UploadQuotaManager = require("../../Globals/Classes/Quotas/UploadQuotaManager");
const fs = require("fs");

const uploadQuotaManager = new UploadQuotaManager();


/**
 * Resolves the OcrModes enum key (e.g. "ENABLED") for a numeric value. Used
 * to namespace the content-addressed storage key so the same file uploaded
 * with two different OCR modes is stored under two different objects.
 */
function getOcrModeKey(ocrModeValue)
{
    for (const [key, value] of Object.entries(ocrModes))
    {
        if (value === ocrModeValue)
        {
            return key;
        }
    }
    return null;
}


/**
 * Computes the global content-addressed key for a (file content, OCR mode)
 * pair. For DISABLED mode the key is just the file hash — so unrelated
 * generation paths (image extraction, syllabus seeded from a doc that was
 * never meant to be OCR'd) share the same storage object as raw uploads.
 * For ENABLED the key includes the mode tag so two users who pick
 * different modes don't collide on the same hash.
 */
function computeContentAddressedKey(originalFileHash, ocrModeValue)
{
    if (ocrModeValue === undefined || ocrModeValue === null || ocrModeValue === ocrModes.DISABLED)
    {
        return originalFileHash;
    }

    const ocrModeKey = getOcrModeKey(ocrModeValue);
    if (!ocrModeKey)
    {
        return originalFileHash;
    }

    return `${originalFileHash}__${ocrModeKey}`;
}


/**
 * Handles the upload of an information source. Expects the InformationSource
 * JSON as a "metadata" query parameter and the file under multipart field
 * "file".
 *
 * Storage contract (content-addressed):
 *   - The CAS key is (sha512(originalFileBytes), ocrMode).
 *   - If any user has already uploaded this exact (file, mode) pair the
 *     existing GCS object is reused — neither the upload nor the OCR work
 *     repeats. This is the "100 users upload the same NCERT textbook with
 *     OCR enabled, OCR runs once" guarantee.
 *   - Per-user dedup uses the same CAS key, so a user can't see two
 *     entries for the same content.
 *
 * OCR contract:
 *   - When ocrMode !== DISABLED, OCR runs through the Agent's OCR_PDF
 *     workflow (the same Python tool used to OCR PDFs generated by the
 *     syllabus/topic-mapping flow). The upload endpoint awaits the Agent
 *     task synchronously so by the time it returns 200 the CAS object IS
 *     the OCR'd PDF.
 *
 * @param {PacketronRequest} request
 * @param {PacketronResponse} response
 * @returns {Promise<void>}
 */
async function handleInformationSourceUpload(request, response)
{
    const user = await getUser(request);

    if (!user)
    {
        response.statusCode = 401;
        response.end("Unauthorized.");
        return;
    }

    const queryParams = await request.getQueryParams();
    const files = await request.getFiles();
    const uploadedFilePath = files.file;

    let fileSizeBytes = 0;
    try
    {
        fileSizeBytes = fs.statSync(uploadedFilePath).size;
    }
    catch (statError)
    {
        fileSizeBytes = 0;
    }

    const quotaCheck = await uploadQuotaManager.check(user.getId(), fileSizeBytes);
    if (!quotaCheck.allowed)
    {
        response.statusCode = 429;
        response.sendJson({
            error: "UPLOAD_QUOTA_EXCEEDED",
            reason: quotaCheck.reason,
            remainingFiles: quotaCheck.remainingFiles,
            remainingBytes: quotaCheck.remainingBytes,
            resetAt: quotaCheck.resetAt
        });
        return;
    }

    const metadataJson = JSON.parse(queryParams.metadata);
    const informationSource = InformationSource.fromJson(metadataJson);

    const originalFileHash = await computeFileSha512Hash(uploadedFilePath);
    const ocrModeValue = informationSource.getOcrMode();
    const contentAddressedKey = computeContentAddressedKey(originalFileHash, ocrModeValue);

    informationSource.setUserId(user.getId());
    informationSource.setHash(contentAddressedKey);

    const bIsDuplicate = await InformationSourceQueryEngine.doesUserAlreadyHaveInformationSourceWithSameContent(
        user.getId(),
        contentAddressedKey,
    );

    if (bIsDuplicate)
    {
        response.statusCode = 409;
        response.end("You have already uploaded a source with the same content.");
        return;
    }

    const informationSourceDirectory = joinPath("/", PersistenceConstants.INFORMATION_SOURCE_DIRECTORY);
    const informationSourcePath = joinPath("/", informationSourceDirectory, contentAddressedKey);

    informationSource.setDirectoryPath(informationSourceDirectory);

    // ── Global CAS check — has anyone already uploaded this (file, mode)? ──
    // If yes, the GCS object is reused and we skip both upload and OCR work.
    const bAlreadyInContentStore = await Persistence.exists(informationSourcePath, storageTargets.GOOGLE_CLOUD_STORAGE);

    if (bAlreadyInContentStore)
    {
        await InformationSourceQueryEngine.saveInformationSource(informationSource);
        await uploadQuotaManager.record(user.getId(), fileSizeBytes);
        response.sendJson(informationSource.toJson());
        return;
    }

    // ── First-time upload for this (file, mode) — move into CAS, then OCR ──
    await Persistence.move(
        uploadedFilePath,
        storageTargets.LOCAL_FILE_SYSTEM,
        informationSourcePath,
        storageTargets.GOOGLE_CLOUD_STORAGE,
    );

    const bOcrRequested = ocrModeValue !== undefined && ocrModeValue !== null && ocrModeValue !== ocrModes.DISABLED;

    if (bOcrRequested)
    {
        // OCR is deferred: schedule the Agent task, return the task ID to
        // the client so its progress bar can poll /Generate/Progress, and
        // run the OCR + DB save in the background. The client treats the
        // upload as fully done only after polling sees status=COMPLETED.
        const ocrTaskDescriptor = new TaskDescriptor({
            type: taskTypes.OCR_PDF,
            executionTarget: taskExecutionTargets.LOCAL,
            payload: { ...informationSource.toJson(), ocrMode: ocrModeValue },
            nextTaskIds: [],
        });

        await TaskManager.setTask(ocrTaskDescriptor);

        const pendingTaskId = ocrTaskDescriptor.getId();

        // Fire and forget — the finalize helper handles save / rollback.
        finalizeOcrUpload({
            ocrTaskDescriptor,
            informationSource,
            informationSourcePath
        }).catch((finalizeError) =>
        {
            console.error(`[InformationSourceUpload] OCR finalize failed for task ${pendingTaskId}: ${finalizeError.message}`);
        });

        await uploadQuotaManager.record(user.getId(), fileSizeBytes);
        response.sendJson({
            ...informationSource.toJson(),
            pendingTaskId
        });
        return;
    }

    await InformationSourceQueryEngine.saveInformationSource(informationSource);
    await uploadQuotaManager.record(user.getId(), fileSizeBytes);
    response.sendJson(informationSource.toJson());
}

module.exports = { handleInformationSourceUpload };
