const GenerationProvenanceQueryEngine = require("../Database/GenerationProvenanceQueryEngine");
const ErrorCodes = require("../../Constants/ErrorCodes");

/**
 * PaidDeckPublishGate
 *
 * Phase 8. Refuses to publish a pipeline-generated paid deck while any BLOCKING
 * verification flag is unresolved.
 *
 * This is a hard block, not a warning, and that is the entire point. This
 * codebase has twice shipped controls that were stamped and never read —
 * contentRetentionModes.TEMPORARY exempted sources from billing while nothing
 * ever deleted them, and the AI-generated deck marker (then called
 * additionalData.protected) marked decks that nothing checked for a long time.
 * Both looked like controls in the code and were not controls in fact.
 * A verification flag that only produced a banner would be the third: the
 * reviewer under time pressure clicks past it, and the wrong constant ships to
 * someone who paid for it.
 *
 * Scope, deliberately narrow. The gate applies ONLY to decks this pipeline
 * generated — decks that have a provenance record. A paid deck built any other
 * way has no verification to be blocked on and publishes exactly as before; this
 * class returns "allowed" for those rather than inventing a requirement.
 *
 * Resolution is explicit and recorded. A flag is cleared by an administrator
 * recording a resolution against it (GenerationProvenanceQueryEngine
 * .recordFlagResolution), which appends a decision beside the original flag
 * rather than editing it. There is no "dismiss all" and no way to clear a flag
 * by regenerating around it.
 */
class PaidDeckPublishGate
{
    /**
     * Resolutions that clear a blocking flag. FIXED means the content was
     * corrected; NOT_A_PROBLEM means the reviewer examined it and judged the
     * flag wrong. Both are decisions someone put their name to, which is what
     * distinguishes them from ignoring the flag.
     */
    static RESOLUTION_FIXED = "FIXED";
    static RESOLUTION_NOT_A_PROBLEM = "NOT_A_PROBLEM";

    static #CLEARING_RESOLUTIONS = new Set([
        PaidDeckPublishGate.RESOLUTION_FIXED,
        PaidDeckPublishGate.RESOLUTION_NOT_A_PROBLEM,
    ]);

    /**
     * Decides whether a deck may be published.
     *
     * @param {string} deckId
     * @return {Promise<{allowed: boolean, reason: (string|null), blockingFlags: object[], detail: (string|null)}>}
     */
    static async evaluate(deckId)
    {
        const provenanceRecord = await GenerationProvenanceQueryEngine.findByDeckId(deckId);

        if (provenanceRecord === null)
        {
            // Not a pipeline-generated deck. Nothing to verify, nothing to block.
            return { allowed: true, reason: null, blockingFlags: [], detail: null };
        }

        const verification = provenanceRecord.verification;

        if (!verification || !Array.isArray(verification.flags))
        {
            // The deck WAS generated by this pipeline but carries no verification
            // result — the stage did not run, or did not complete. Refused: an
            // unverified deck is not a verified one, and treating a missing
            // result as a pass is precisely how a control becomes decorative.
            return {
                allowed: false,
                reason: ErrorCodes.PUBLISH_BLOCKED_BY_VERIFICATION_FLAGS,
                blockingFlags: [],
                detail: "This deck was generated by the paid-deck pipeline but has no verification result. Re-run verification before publishing.",
            };
        }

        const resolvedFlagIndices = PaidDeckPublishGate.#collectResolvedFlagIndices(provenanceRecord.flagResolutions);

        const unresolvedBlockingFlags = [];
        for (let flagIndex = 0; flagIndex < verification.flags.length; flagIndex++)
        {
            const flag = verification.flags[flagIndex];
            if (flag.severity !== "blocking")
            {
                continue;
            }
            if (resolvedFlagIndices.has(flagIndex))
            {
                continue;
            }
            unresolvedBlockingFlags.push({ flagIndex: flagIndex, ...flag });
        }

        if (unresolvedBlockingFlags.length > 0)
        {
            return {
                allowed: false,
                reason: ErrorCodes.PUBLISH_BLOCKED_BY_VERIFICATION_FLAGS,
                blockingFlags: unresolvedBlockingFlags,
                detail: `${unresolvedBlockingFlags.length} blocking verification flag(s) are unresolved.`,
            };
        }

        return { allowed: true, reason: null, blockingFlags: [], detail: null };
    }

    static #collectResolvedFlagIndices(flagResolutions)
    {
        const resolvedFlagIndices = new Set();

        for (const resolution of (flagResolutions || []))
        {
            if (typeof resolution.flagIndex !== "number")
            {
                continue;
            }
            if (PaidDeckPublishGate.#CLEARING_RESOLUTIONS.has(resolution.resolution))
            {
                resolvedFlagIndices.add(resolution.flagIndex);
            }
        }

        return resolvedFlagIndices;
    }

    /**
     * True when the supplied string is a resolution that clears a flag. Used by
     * the endpoint that records resolutions so an arbitrary string cannot be
     * posted as a clearing decision.
     */
    static isClearingResolution(resolution)
    {
        return PaidDeckPublishGate.#CLEARING_RESOLUTIONS.has(resolution);
    }
}

module.exports = PaidDeckPublishGate;
